### ISSUE TITLE
Multiply node breaks the graph

### ISSUE THREAD

**Issue by mert-dev-acc** [iBicha/ImageEffectGraph#6]
**Unity Version: 2018.3.0b9**
When try to connect a multiply node and multiply Maintexture output with color node then assign it image effect node, it doesnt work and become one of "not compiled shaders". Middle of screen became pink with a triangle. (There is a cube over there.) Error like this:

![image](https://user-images.githubusercontent.com/3215742/48665461-c8019480-eabf-11e8-9c7b-10272b466a4a.png)

 Screenshots as follows:

![image](https://user-images.githubusercontent.com/3215742/48665426-106c8280-eabf-11e8-9b83-a2a8a7ff2d45.png)

![image](https://user-images.githubusercontent.com/3215742/48665424-064a8400-eabf-11e8-82f9-8c9c73770677.png)

**Comment by iBicha** [comment]
Good catch! Thank you for the bug report.
This is due to the fact that shader graph expects from the shader generator to implement certain functions, `SRGBToLinear` being one of them (actually the node requiring this function is the color node, not the multiply one). While SRP (Light weight RP and HDRP) implement this, the legacy shader library doesn't. I'm studying whether this should be implemented separately for each function, or to drop support for legacy graphics at once, since shader graph is supposed to work with SRP.
I will try to put a solution in place soon.
Thanks

**Comment by mert-dev-acc** [comment]
Interesting, thanks for explanation buddy!
You are welcome, I'll be following for updates.

**Comment by iBicha** [comment]
Hi again!
I did work on a work around for this while I was on an airplane and I didn't have internet to push it.
Please let me know if the latest version solves the issue

**Comment by mert-dev-acc** [comment]
Sounds good! I'll take a look asap. Although, did you push the latest version 5 days ago ? Because I dont see any new commit.

**Comment by iBicha** [comment]
> Sounds good! I'll take a look asap. Although, did you push the latest version 5 days ago ? Because I dont see any new commit.

Yes in deed, the fix is already pushed

**Comment by mert-dev-acc** [comment]
Hey there! Sorry for it took so long, I was busy with job. So I finally tested it and it looks great!
Graph:
![image](https://user-images.githubusercontent.com/3215742/49656067-6e044700-fa4d-11e8-9eaa-b3af85a5e731.png)
Result:
![image](https://user-images.githubusercontent.com/3215742/49656086-7a889f80-fa4d-11e8-8383-ea4dae650fee.png)

**Comment by iBicha** [comment]
Great. Glad this is issue is solved.
